### ISSUE TITLE
Versions after 1.0.1 do not open on Mac

### ISSUE THREAD

**Issue by kkbrass** [ugcs/UgCS-GeoHammer#10]
Running macOS Catalina 10.15.4
 
Have Java 8.261 installed.

Version 1.0.1 of GeoHammer opens up. Versions after that do not. Tried multiple. Reinstalling Java did not help.

<img width="595" alt="Screenshot 2020-09-24 at 12 07 12" src="https://user-images.githubusercontent.com/11043861/94125035-7c0f9b80-fe5e-11ea-8a3b-93df963f5024.png">

**Comment by a-kogun** [comment]
Fixed in 1.1.8-SNAPSHOT
