### ISSUE TITLE
Program Not Running

### ISSUE THREAD

**Issue by abdulhafidz6** [ugcs/UgCS-GeoHammer#16]
Hi Dear,

I just downloaded the release v.1.1.1. 
I have java installed previously. But when I run the exe or .jar or the start.cmd file, the program is not opening nor showing anything.
I tried to run the .jar file manually through cmd, and it showed like this:

C:\Users\hp>cd C:\java\UgCS-GeoHammer-v.1.1.1

C:\java\UgCS-GeoHammer-v.1.1.1>start.cmd

C:\java\UgCS-GeoHammer-v.1.1.1>java -Xmx2g -cp geohammer-jar-with-dependencies.jar com.ugcs.gprvisualizer.app.MainGeoHammer
Error: Could not find or load main class com.ugcs.gprvisualizer.app.MainGeoHammer
Caused by: java.lang.NoClassDefFoundError: javafx/application/Application

Really appreciate your helps. Thankyou

**Comment by rajandmk** [comment]
> Hi Dear,
> 
> I just downloaded the release v.1.1.1. I have java installed previously. But when I run the exe or .jar or the start.cmd file, the program is not opening nor showing anything. I tried to run the .jar file manually through cmd, and it showed like this:
> 
> C:\Users\hp>cd C:\java\UgCS-GeoHammer-v.1.1.1
> 
> C:\java\UgCS-GeoHammer-v.1.1.1>start.cmd
> 
> C:\java\UgCS-GeoHammer-v.1.1.1>java -Xmx2g -cp geohammer-jar-with-dependencies.jar com.ugcs.gprvisualizer.app.MainGeoHammer Error: Could not find or load main class com.ugcs.gprvisualizer.app.MainGeoHammer Caused by: java.lang.NoClassDefFoundError: javafx/application/Application
> 
> Really appreciate your helps. Thankyou

I too have same problem. 
com.ugcs.gprvisualizer.app.MainGeoHammer not found

**Comment by a-kogun** [comment]
Please check the current version, 1.1.8 - for now it's bundled with Java Runtime 21 custom image for the appropriate platform.
