### ISSUE TITLE
Incorrect counting of traces in position.csv files (should ignore rows without trace number in position.csv)

### ISSUE THREAD

**Issue by adobrovolskiy-ugcs** [ugcs/UgCS-GeoHammer#24]
Steps to reproduce the problem:

1. drop sgy file
2. drop position.csv file
3. will see the message as below

![image](https://user-images.githubusercontent.com/21184180/177545736-b5b46414-5605-41dd-923b-047334774ee1.png)

files to reproduce the problem are in archive

[2022-04-29 Zond Aero 500 gas pipes.zip](https://github.com/ugcs/UgCS-GeoHammer/files/9054517/2022-04-29.Zond.Aero.500.gas.pipes.zip)

Geohammer should count only rows with valid trace number (numbers from 0 and up), in columns like "GPR:Trace" or "zGPR:Trace". Please note that for different GPR models column name may have different prefics, but "GPR:Trace" will be the same.

**Comment by IManuilov** [comment]
ready
