### ISSUE TITLE
Implement KML file import to display marks on the map and insert marks into SGY files

### ISSUE THREAD

**Issue by adobrovolskiy-ugcs** [ugcs/UgCS-GeoHammer#25]
Story: we regularly have to analyze the data from test ranges with known targets (their coordinates). It is very time consuming process to aligh current data with known coordinates.

Idea is to implement possibility to import KML file with <Placemark> tags from KML and display flags on the map as on the image below.

![image](https://user-images.githubusercontent.com/21184180/177548792-11be8b8b-1987-4fc7-b13b-9350691660dd.png)

KML file can be  dropped into Geohammer window.

After the KML file is imported and marks (flags) displayed on the map, Geohammer should ask "Do you want to insert marks into SEG-Y file?" yes/no.

If answers is Yes, marks should be inserted into SEG-Y files. Otherwise they will be displayed on the map only.

Important:

- on the map placemarks should be displayed in their original position using coordinates
- when marks are to be inserted into SEG-Y file, nearest trace from all loaded profiles should be found. The similar functionality is already implemented in Geohammer for the processing of double-click in the map - Ballon is displayed on the nearest trace of loaded profile(s)
- marks insertion functionality should be supported for SEG-Y files only (not for GSSI files).

**Comment by adobrovolskiy-ugcs** [comment]
One more important note: during the KML file import Geohammer should look for tag <coordinates> only somewhere inside of all <Placemark> nodes in KML. It should not rely on the presence of other tags or hierarchy of tags.

**Comment by IManuilov** [comment]
@adobrovolskiy-ugcs do you have an example of kml file with sgy written on the same area?

**Comment by adobrovolskiy-ugcs** [comment]
Attached is KML file with "point" targets

[Balozi-test_placemarks.zip](https://github.com/ugcs/UgCS-GeoHammer/files/9268179/Balozi-test_placemarks.zip)

Data sets gathered in the same place:

https://files.ugcs.com/s/R563w6nHdnxALkm
https://files.ugcs.com/s/B5TNQcfa49yTFGJ
https://files.ugcs.com/s/RoFwg3zq2EFaQwy
