### ISSUE TITLE
When select goodle as map source, map doesn't load (when switch between here, goodle, off, ...)

### ISSUE THREAD

**Issue by adobrovolskiy-ugcs** [ugcs/UgCS-GeoHammer#37]
![image](https://github.com/ugcs/UgCS-GeoHammer/assets/21184180/5ff74454-fd37-4dec-8fae-4e011ee77575)

**Comment by emmaemmstein** [comment]
I am experiencing same, I can't seem to view the map
![Capture](https://github.com/ugcs/UgCS-GeoHammer/assets/97186535/eb015031-6f20-4649-bfc1-36725444000b)

**Comment by a-kogun** [comment]
here.com map was fixed in 1.1.9 release - https://github.com/ugcs/UgCS-GeoHammer/releases/tag/v.1.1.9
