### ISSUE TITLE
Allow to load SEG-Y files without coordinates

### ISSUE THREAD

**Issue by adobrovolskiy-ugcs** [ugcs/UgCS-GeoHammer#4]
Currently, GeoHammer will not load SEG-Y without coordinates with a message about the wrong file format. The proposal is to allow the loading of such files but not to display anything in the map window.

**Comment by IManuilov** [comment]
> Currently, GeoHammer will not load SEG-Y without coordinates with a message about the wrong file format. The proposal is to allow the loading of such files but not to display anything in the map window.

Could you give me an example of such file?

**Comment by adobrovolskiy-ugcs** [comment]
[DAT_0050_CH_1.zip](https://github.com/ugcs/UgCS-GeoHammer/files/4804257/DAT_0050_CH_1.zip)

**Comment by IManuilov** [comment]
Done
