### ISSUE TITLE
Export empty *.kml

### ISSUE THREAD

**Issue by ASjomins** [ugcs/UgCS-GeoHammer#49]
When trying to open the *.kml file exported from Geohammer 1.1.10 get an error: empty kml file.
![image](https://github.com/ugcs/UgCS-GeoHammer/assets/116797077/1b4ebc76-ddb3-405c-ab50-68a6f38986fd)

**Comment by a-kogun** [comment]
Fixed in https://github.com/ugcs/UgCS-GeoHammer/commit/22a4a319e785555c7391bda0323faa36960692d1
