### ISSUE TITLE
Remember folder for GeoTIFF export 

### ISSUE THREAD

**Issue by IManuilov** [ugcs/UgCS-GeoHammer#6]

**Comment by adobrovolskiy-ugcs** [comment]
And for KML also

**Comment by IManuilov** [comment]
> And for KML also
Do you mean the same last used folder for tiff and kml, or different folders for tiff and for kml?

if user saved tiff, should this folder be proposed for saving KML ?

**Comment by adobrovolskiy-ugcs** [comment]
yes, the same folder for any export

**Comment by IManuilov** [comment]
Done
