### ISSUE TITLE
If geohammer started from Windows Start menu, it can't recognise file types

### ISSUE THREAD

**Issue by adobrovolskiy-ugcs** [ugcs/UgCS-GeoHammer#71]
1. start writing "geohammer" in Windows Start menu, and run it by click when it found
![image](https://github.com/user-attachments/assets/1aff03c6-31cb-4667-a803-90cc4cd40cc3)

2. next drag&drop data file
![image](https://github.com/user-attachments/assets/d91d8bdd-67ac-4a5b-855a-3c62b776a81b)

if I start geohammer from it's folder, it recognises the same files

**Comment by a-kogun** [comment]
The resolution of the templates folder has been fixed. Additionally, if the templates for the files are not found, a message will be displayed on startup.

![telegram-cloud-photo-size-2-5266970085472462856-x](https://github.com/user-attachments/assets/8b4b0283-0b7e-4f2a-9b70-b89731e5b526)
