### ISSUE TITLE
GeoHammer can't open attached file - "probably file has incorrect format"

### ISSUE THREAD

**Issue by adobrovolskiy-ugcs** [ugcs/UgCS-GeoHammer#9]
but it can be opened by Prizm2 software

[2018-02-19-20-29-44-gpr.zip](https://github.com/ugcs/UgCS-GeoHammer/files/4891075/2018-02-19-20-29-44-gpr.zip)

**Comment by IManuilov** [comment]
![coordinates](https://user-images.githubusercontent.com/49779335/87022679-83b89000-c1df-11ea-833e-00a9e86e5522.png)

I fixed the problem, file is opened no. But this file apparently has wrong encoded coordinates

**Comment by IManuilov** [comment]
![coordinates2](https://user-images.githubusercontent.com/49779335/87023065-f9246080-c1df-11ea-874d-846abdc899f3.png)
Relative positions of traces are correct, but the place on the earth  is wrong

**Comment by adobrovolskiy-ugcs** [comment]
OK, please close it. I see that there are wrong coordinates in the file.
